### ISSUE TITLE
function 'element_validate_integer_positive' not found or invalid function

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/iframe#1]
We've removed the need for these integer specific validation functions in Backdrop since we now have Number form elements. Here's the change record: https://api.backdropcms.org/node/43955

Here's the current height field:
```php
$element['height'] = array(
        '#type' => 'textfield',
        '#title' => t('height'),
        '#default_value' => $fheight,
        '#size' => 4,
        '#maxlength' => 4,
        '#weight' => 5,
        '#delta' => $delta,
        '#element_validate' => array('element_validate_integer_positive'),
      );
```
Here's what we should change it to:
```php
$element['height'] = array(
        '#type' => 'number',
        '#title' => t('Height'),
        '#default_value' => $fheight,
        '#min' => 0,
        '#weight' => 5,
        '#delta' => $delta,
      );
```

**Comment by djzwerg** [comment]
Could that be solved with a PR?

**Comment by jenlampton** [comment]
Hrm, I don't think we can switch to using a number field here, because this field takes both a number and a percent. I'm posting the patch I'm currently using, which removes the function and also contians some minor form cleanup. https://github.com/backdrop-contrib/iframe/pull/3
