### ISSUE TITLE
Maintainer Request / Release Request

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/iframe#2]
We recently got a [request for someone to port](https://github.com/backdrop-ops/contrib/issues/355) the D7 [Link iFrame Formatter](https://www.drupal.org/project/link_iframe_formatter) module to Backdrop CMS. As far as I can tell, this one does the same things, but is not available in an official release. 

Just checking to see if there is something I can do to help get an official release for this module, including becoming a co-maintainer or even full maintainer if the current maintainer no longer has the time/resources.

**Comment by yorkshire-pudding** [comment]
@stpaultim - did you hear anything back?  Looks like it may be abandoned and need taking over.

**Comment by stpaultim** [comment]
@yorkshire-pudding No, I never heard back. I was mostly responding to a request in the forum, so I don't have a personal interest in this module at this time.

**Comment by juanolalla** [comment]
I've ported [link_iframe_formatter](https://github.com/backdrop-contrib/link_iframe_formatter) and released it. Closing.
